 INSERT INTO BANK_CODES (BANK_CODE, BANK_NAME) VALUES
 ('044', 'ACCESS BANK PLC'),
 ('050', 'ECOBANK NIGERIA PLC'),
 ('070', 'FIDELITY BANK PLC'),
 ('011', 'FIRST BANK OF NIGERIA PLC'),
 ('017', 'ZENITH BANK'),
 ('069', 'INTERCONTINENTAL BANK PLC');


